require:
  - rubocop-rspec
inherit_mode:
  merge:
    - Exclude
AllCops:
  NewCops: enable
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
RSpec/FilePath:
  Enabled: false
Style/Documentation:
  Enabled: false
#-------------------------------------------------------------------------------
RSpec/ExampleLength:
  Exclude:
    - spec/integration/repository_spec.rb
    - spec/unit/repository_spec.rb
    - spec/unit/structs/psc_stream_spec.rb
RSpec/MessageSpies:
  Exclude:
    - spec/unit/repository_spec.rb
    - spec/unit/services/es_index_creator_spec.rb
RSpec/MultipleExpectations:
  Exclude:
    - spec/integration/repository_spec.rb
    - spec/unit/repository_spec.rb
    - spec/unit/structs/address_spec.rb
    - spec/unit/structs/company_record_spec.rb
    - spec/unit/structs/corporate_entity_spec.rb
    - spec/unit/structs/date_of_birth_spec.rb
    - spec/unit/structs/identification_spec.rb
    - spec/unit/structs/individual_spec.rb
    - spec/unit/structs/legal_person_spec.rb
    - spec/unit/structs/name_elements_spec.rb
    - spec/unit/structs/psc_stream_event_spec.rb
    - spec/unit/structs/psc_stream_spec.rb
    - spec/unit/structs/statement_spec.rb
    - spec/unit/structs/super_secure_spec.rb
RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/integration/repository_spec.rb
RSpec/NamedSubject:
  Exclude:
    - spec/integration/repository_spec.rb
    - spec/unit/repository_spec.rb
    - spec/unit/services/es_index_creator_spec.rb
RSpec/StubbedMock:
  Exclude:
    - spec/unit/repository_spec.rb
RSpec/VerifiedDoubles:
  Exclude:
    - spec/unit/repository_spec.rb
    - spec/unit/services/es_index_creator_spec.rb
