version: "3.8"
services:
  sources-psc:
    build:
      context: .
      target: dev
    env_file: .env
    networks:
      - elasticsearch
      - sources
    restart: on-failure
    volumes:
      - ${DC_SOURCES_PSC_LIB_REGISTER_COMMON:-.dockerempty}:/home/x/lib/register-common
      - ./bin:/home/x/r/bin
      - ./Gemfile.lock:/home/x/r/Gemfile.lock
      - ./Gemfile:/home/x/r/Gemfile
      - ./lib:/home/x/r/lib
      - ./register_sources_psc.gemspec:/home/x/r/register_sources_psc.gemspec
      - ./spec:/home/x/r/spec
networks:
  elasticsearch: {}
  sources: {}
